set viminfofile=$XDG_STATE_HOME/vim/viminfo

syntax on

set title
set number relativenumber

set incsearch
set nohlsearch
set smartcase

set laststatus=2
set showcmd

filetype plugin indent on
set autoindent
set shiftwidth=2
set tabstop=2

autocmd FileType tex setlocal indentexpr=
